### ISSUE TITLE
Won't compile with python bindings enabled

### ISSUE THREAD

**Issue by hynese** [gmarcais/Jellyfish#74] opened 2016-11-01 16:36 UTC
Greetings,

I'm trying to make and I get the following error:

```
./configure --prefix=/opt/apps/jellyfish/jellyfish-2.2.6/build --enable-python-binding=/opt/apps/jellyfish/jellyfish-2.2.6/build/python-binding --with-sse --with-gnu-ld --enable-static=no



 make
make  all-am
make[1]: Entering directory `/opt/apps/jellyfish/jellyfish-2.2.6'
  CXX      lib/rectangular_binary_matrix.lo
  CXX      lib/mer_dna.lo
  CXX      lib/storage.lo
  CXX      lib/allocators_mmap.lo
  CXX      lib/misc.lo
  CXX      lib/int128.lo
  CXX      lib/thread_exec.lo
  CXX      lib/jsoncpp.lo
  CXX      lib/time.lo
  CXX      lib/generator_manager.lo
  CXXLD    libjellyfish-2.0.la
**/opt/gridware/pkg/el6/compilers/gcc/4.4.7/lib/../lib/libstdc++.so: could not read symbols: File in wrong format
collect2: ld returned 1 exit status
make[1]: *** [libjellyfish-2.0.la] Error 1
make[1]: Leaving directory `/opt/apps/jellyfish/jellyfish-2.2.6'
make: *** [all] Error 2**
```

I'm using gcc-4.4.7 and on CentOS 6. I also tried with gcc-5.1 and gcc-4.7.3 to no avail.

**Comment by gmarcais** [comment] 2016-11-03 17:22
Hi Hynese,
I am not quite sure what the problem is, but I think it is with your compiler installation. I created a Centos6 docker image and I can compile (almost) without problem using the default compiler, gcc 4.4. This is the Dockerfile:

```Dockerfile
FROM centos:centos6
LABEL description="Compilation on CentOS6."
RUN yum -y install gcc-c++ python-devel
CMD ["/bin/bash"]
```

Then I could compile after one modification (nullptr -> NULL) as follows:

```Shellscript
curl -L -O https://github.com/gmarcais/Jellyfish/releases/download/v2.2.6/jellyfish-2.2.6.tar.gz
tar zxf jellyfish-2.2.6.tar.gz
cd jellyfish-2.2.6
sed -e 's/nullptr/NULL/' swig/python/swig_wrap.cpp
./configure --enable-python-binding
make
```

Can you compile other C++ programs? Or only Jellyfish is causing you problems?

**Comment by hynese** [comment] 2016-11-03 17:37
Thank you for investigating that. That's very kind of you.

I'm in a HPC environment here. 

We have c++ installed to a non-standard location (e.g. /opt/gridware/pkg/el6/compilers/gcc/4.4.7/lib/../lib/libstdc++.so)

This is a well tested gcc installation. I tried newer versions too. And gcc 5.1

**Comment by hynese** [comment] 2016-11-04 09:41
So I deleted everything and started again. It seems the .so error above has gone away.

I now get the following error:

```
make
make  all-am
make[1]: Entering directory `/opt/apps/jellyfish/jellyfish-2.2.6'
  CXX      lib/rectangular_binary_matrix.lo
  CXX      lib/mer_dna.lo
  CXX      lib/storage.lo
  CXX      lib/allocators_mmap.lo
  CXX      lib/misc.lo
  CXX      lib/int128.lo
  CXX      lib/generator_manager.lo
  CXXLD    libjellyfish-2.0.la
  CXX      swig/python/swig_python__jellyfish_la-swig_wrap.lo
swig/python/swig_wrap.cpp: In member function 'const MerDNA* StringMers::next_mer__()':
swig/python/swig_wrap.cpp:3703: error: 'nullptr' was not declared in this scope
make[1]: *** [swig/python/swig_python__jellyfish_la-swig_wrap.lo] Error 1
make[1]: Leaving directory `/opt/apps/jellyfish/jellyfish-2.2.6'
make: *** [all] Error 2
```

**Comment by gmarcais** [comment] 2016-11-04 14:35
Yes, that is a known problem, that is fixed by the `sed` command in the code snippet above (which I just edited).

**Comment by hynese** [comment] 2016-11-04 15:11
It worked!

`sed -i.bak -e 's/nullptr/NULL/' swig/python/swig_wrap.cpp`

**Closed** 2017-03-20 18:36 UTC
